### ISSUE TITLE
US 02.05.01 - Organizer: Send notification to chosen entrants

### ISSUE THREAD

**Issue by AidenPeacock** [The-Quacks/quacks-app#13]
US 02.05.01 As an organizer I want to send a notification to chosen entrants to sign up for events

### **Acceptance Criteria**

* Show confirmation button on entrant selection activity 
  * when this button is clicked, the app will take select those entrants from the total pool, and accessing their email that is connected to their account, send them a standard email that is personalized to them with their name

* Unit tests written and passed
* Functionality documented

**Comment by jpaanane** [comment]
The organizer side is done-- Marko is working on completing the notification handler to send it to the entrant
