### ISSUE TITLE
US 02.07.01 - Organizer: Send notifications to all entrants on waiting list

### ISSUE THREAD

**Issue by AidenPeacock** [The-Quacks/quacks-app#21]
US 02.07.01 As an organizer I want to send notifications to all entrants on the waiting list

### **Acceptance Criteria**

* On the entrants invited activity, show a notify all button that will display an activity with a text field, and a confirm button
  * the text field will be a custom email body the organizer can specify before sending to all entrants in the list
  * the confirm button will send this custom email
* Unit tests written and passed
* Functionality documented

**Comment by jpaanane** [comment]
The organizer side is done-- Marko is working on completing the notification handler to send it to the entrant
